Repository Bugs5382/node-hl7-server, pull requests merged in 2024-06, with the labels that each got.

#77 feat: added MSH override with spec being passed over
  README.md
  __tests__/hl7.end2end.test.ts
  package.json
  src/server/inbound.ts
  src/server/modules/sendResponse.ts
  src/utils/normalize.ts
Labels: enhancement

#82 feat: update packages
  .eslintignore
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/question.md
  .github/workflows/ci.yaml
  .github/workflows/dependabot-action.yml
  .github/workflows/deploy-ci.yaml
  .github/workflows/pr-title-check.yml
  .github/workflows/pr-unit-tests.yml
  README.md
  __tests__/tsconfig.json
  package.json
  src/server/inbound.ts
  src/tsconfig.build.json
  src/tsconfig.cjs.json
  src/tsconfig.esm.json
  src/tsconfig.json
  src/tsconfig.types.json
  tsconfig.base.json
  tsconfig.build.json
  tsconfig.esm.json
  tsconfig.json
  typedoc.json
Labels: documentation, enhancement, dependencies

#83 feat: update
  .eslintignore
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/question.md
  .github/workflows/ci.yaml
  .github/workflows/dependabot-action.yml
  .github/workflows/deploy-ci.yaml
  .github/workflows/pr-title-check.yml
  .github/workflows/pr-unit-tests.yml
  CHANGELOG.md
  README.md
  __tests__/tsconfig.json
  package.json
  src/server/inbound.ts
  src/tsconfig.build.json
  src/tsconfig.cjs.json
  src/tsconfig.esm.json
  src/tsconfig.json
  src/tsconfig.types.json
  tsconfig.base.json
  tsconfig.build.json
  tsconfig.esm.json
  tsconfig.json
  typedoc.json
Labels: documentation, enhancement, dependencies

#84 chore: fix docs
  .github/workflows/deploy-ci.yaml
Labels: documentation

#85 chore: fix docs
  .github/workflows/deploy-ci.yaml
Labels: documentation

#86 fix(60): Ensure large messages like encapsulated PDFs are not split and ignored by the server
  __tests__/__utils__/index.ts
  __tests__/hl7.end2end.test.ts
  src/server/inbound.ts
Labels: bug, enhancement
